---
title: "Untitled"
author: "Astrid Langsrud, Håkon Gryvill"
date: "25 4 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Keywords

Issues to be addressed:

# Introduction
Describe the problem you want to study.
Why is this interesting?
What prior knowledge do you have?
What do you want to achieve?

In our experiment we want to study how different factors affect our responsiveness. 
The experiment was performed in the following way: 
A ruler is dropped at a random point in time. The test person's responsiveness is determined by how far down the ruler is caught.
This experiment is of interest because it gives us an idea of how mental and physical distraction affects our responsiveness. (Skriv mer svada)



# Selection of factors and levels:
Which factors do you think are relevant to the problem described above?
Do you expect an interaction between some of the factors?
Which levels should be used, and why do you think these are reasonable?
How can you control that the factors really are at the desired level?

We are looking at the following factors in our experiment: the gender of the test person, physical distraction (i. e., whether the person has been spinning around or not) and mental distraction (the person has to talk about a given subject during the experiment).
In advance we expected that at least physical distraction would decrease the responsiveness. 

# Selection of response variable:
Which response variable will provide information about the problem described above?
Are there several response variables of interest?
How should the response be measured?
What can you say about the accuracy of these measurements?

# Choice of design:
2 k factorial.
2 k–p fractional factorial or other design?
Desired resolution of the design?
Is it necessary or desirable to use a blocked design?
Is it necessary or desirable with replicates?

# Implementation of the experiment:
Randomization.
Describe any problems with the implementation (maybe the randomization was not followed?).
Is each experiments a genuine run replicate, that is reflects the total variability of the experiment? (Each trial should be a performed independently and constitute a full trial.)

# Analysis of data
Calculation of effects and assessment of statistical significance.
Check the assumptions. Important: residual plots!

# Conclusion and recommendations:
Which conclusions can you draw from the experiment?
Interpretation of significant effects, main and interaction plots.
Remember that plots are illustrative and very useful for demonstrations.

